version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: tv_shows_api
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tv_shows_api_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: bundle exec rails server -b 0.0.0.0
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://tv_shows_api:password@db:5432/tv_shows_api_development
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: development

volumes:
  postgres_data: